### ISSUE TITLE
拼团人数不能自动更新

### ISSUE THREAD

**Issue by GSCong** [liujiaqi222/pdd_miniprogram#5]
比如我在小程序内发布任务时还差三个人，而此时有一个人没有通过小程序，而是通过拼多多软件加入了拼团，此时正确的人数应该是还差两个人，但是小程序内依旧显示还差三个人。

**Comment by liujiaqi222** [comment]
这个会自动更新的，就是我现在设置的定时任务是20分钟请求pdd全量更新一次。

**Comment by GSCong** [comment]
我发现了。还有一个问题就是小程序内发布的内容是实时更新吗，为什么总有人发布同样的任务😒

**Comment by liujiaqi222** [comment]
> 

对用户发布的拼团是立即更新，可能用户会发布相同的拼单商品，但是绝对不是相同的拼团，一定是不同的拼团

**Comment by 871690991** [comment]
想问下后端，如何获取这个团差几个人这个咋实现的通过爬虫吗，拼多多开放没有相关的api
