### ISSUE TITLE
几人成团

### ISSUE THREAD

**Issue by Jerome786** [liujiaqi222/pdd_miniprogram#7]
你好 我想咨询一下 几人成团这个信息是从哪里获取的

**Comment by liujiaqi222** [comment]
这个代码里面有写 [https://github.com/liujiaqi222/pdd_miniprogram/blob/main/server/src/util/index.ts#L64](https://github.com/liujiaqi222/pdd_miniprogram/blob/main/server/src/util/index.ts#L64)

**Comment by Jerome786** [comment]
还有个问题就是 你是怎么拿到pdd的cookie的 代码没看到

**Comment by liujiaqi222** [comment]
> 还有个问题就是 你是怎么拿到pdd的cookie的 代码没看到 轮询更新也会 出现cookie失效吧 是怎么解决这个问题的

获取cookie，就是你登录pdd的账户就好了，失效的话，因为你每天都在请求，所以目前还没遇到失效

**Comment by 871690991** [comment]
我现在是爬虫 经常失效 换了很多个账号了   每几天失效一次
